import type { Metadata } from 'next'
import {Nunito} from 'next/font/google'
import './globals.css'
import Modals from './modals/modals'
import LoginModals from './modals/login-modals'
import Navbar from '../components/navbar'
import RegisterModal from './modals/register-modals'
import { Toaster } from 'react-hot-toast'
import { authOptions } from './api/auth/[...nextauth]/route'
import { getServerSession } from 'next-auth'
import Sidebar from '@/components/sidebar'



const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <LoginModals />
        <RegisterModal />
        <div className='grid grid-cols-5 gap-1 w-full'>
          <div className='bg-blue-600 col-span-1 '>
            <Sidebar />
          </div>
          <div className="bg-red-200 col-span-4 w-full">
            <Navbar name ={session?.user?.name}/>
            {children}
            <Toaster/>
          </div>
        </div>
        </body>
    </html>
  )
}
