import type { Metadata } from 'next'
import {Nunito} from 'next/font/google'
import './globals.css'
import Modals from './modals/modals'
import LoginModals from './modals/login-modals'
import Navbar from '../components/navbar'
import RegisterModal from './modals/register-modals'
import { Toaster } from 'react-hot-toast'
import { authOptions } from './api/auth/[...nextauth]/route'
import { getServerSession } from 'next-auth'
import Sidebar from '@/components/sidebar'
import useSidebar from './hooks/useSidebar'
import SidebarCover from '@/components/sidebar-cover'
import NavbarCover from '@/components/navbar-cover'



const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <LoginModals />
        <RegisterModal />
        <div className='flex justify-start items-start w-full '>
          <SidebarCover >
            <Sidebar />
          </SidebarCover>
            <NavbarCover >
              <Navbar 
                name ={session?.user?.name}
                img = {session?.user?.image}
                email = {session?.user?.email}
                />
              {children}
            <Toaster/>
          </NavbarCover>
        </div>
        </body>
    </html>
  )
}
